### ISSUE TITLE
AAAAAAAAAAAAAAAAAAAAAAA

### ISSUE THREAD

**Issue by Sandwhich253989** [A-Paint-Brush/Flappy-Bird#1]
hi lol

**Comment by A-Paint-Brush** [comment]
Um hi. Are you just getting fustrated by the game? 🤨

**Comment by Sandwhich253989** [comment]
no lol i tested it out and its very nice

**Comment by Sandwhich253989** [comment]
no lmao i was testing it out , its very good

**Comment by Sandwhich253989** [comment]
no lol i tested it out and its very good

**Comment by A-Paint-Brush** [comment]
Closed as there's no real issue 🙃

**Comment by Sandwhich253989** [comment]
xdd imagine chatting through issues section lmfaooo
